import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProviders } from "./components/AuthProviders";
import AuthLayout from "./components/AuthLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProviders>
          <AuthLayout>{children}</AuthLayout>
        </AuthProviders>
      </body>
    </html>
  );
}
